### ISSUE TITLE
Incorporate references to Technical Decisions incorporated in PP

### ISSUE THREAD

**Issue by amasino** [commoncriteria/application#165]
Apart from Version Control, it would be desirable to include the list of technical decisions applied to the Protection Profile. This will allow evaluators to know the level of update of the repository with regards to NIAP TDs.

**Comment by jmcdaniels** [comment]
A new version will apply all  outstanding TDs .

NIAP will post all TDs that apply on their website.

We will be working to follow this plan for TDs moving forward:

https://github.com/commoncriteria/pp-template/wiki/Technical-Decisions
