### ISSUE TITLE
Current draft version has duplicate conformance statements

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/application#166]
The current draft version for some reason has duplicate conformance statements. The first look like some sort of boilerplate that is fairly generic, and the second set is the correct set.

Not sure where it is coming from, the XML seems to be correct (but I'm not sure).

**Comment by bplu** [comment]
Thanks for pointing this out. I am currently taking a look into this to see where the first set of claims is coming from. The second set is in fact the correct set of conformance statements.

**Comment by bplu** [comment]
Fixed the issue.
