### ISSUE TITLE
Apply NiT RFI 202119?

### ISSUE THREAD

**Issue by KSinitski** [commoncriteria/application#170]
As Entropy Annex is the same, does it make sense to apply RFI 202119?

.old> The documentation will describe the operation of the entropy source to include how entropy is
produced, and how unprocessed (raw) data can be obtained from within the entropy source for testing
purposes. ./old>

shall be replaced by

.new>The documentation shall describe how unprocessed (raw) data was obtained for the analysis. This
description shall be sufficiently detailed to explain at what point in the entropy source model the data
was collected and what effects, if any, the process of data collection had on the overall entropy
generation rate. ./new>

**Comment by jmcdaniels** [comment]
Updated.

**Comment by OlegAndrianov** [comment]
This change has no meaning now with new requirements to provide ESV certificate all this have to be changed and replaced with the new version of the Entropy Annex, that NIAP has to develop.
