### ISSUE TITLE
package updates for CC:2022 APE_CCL.1-7

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/application#173]
In CC:2022, the APE_CCL.1-7 workunit requires the evaluator to check the PP for packages that the PP claims conformance to and then check the packages themselves to ensure they have certain things present that the CEM requires. As part of updating the App PP to be consistent with CC:2022 it was observed that the SSH and TLS packages do not contain all of the materials that this workunit requires, so further updates will need to be made to those for the PP to conform to the new edition of the CC.

**Comment by jmcdaniels** [comment]
Completed.
