### ISSUE TITLE
should SWID be mandatory now?

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/application#175]
App PP v1.4 has an app note in FPT_IDV_EXT.1 that says SWID tags will be required in "the next major release" of the PP. Based on this, we should consider whether that is still applicable and, if so, should update the SFR accordingly. Since I haven't heard anything either way, I wanted to check.

**Comment by mbdowne** [comment]
Yes, this should be mandatory.

**Comment by mbdowne** [comment]
Sole source, assignment and selection should all be removed.

**Comment by jfisherbah** [comment]
SFR updated for SWID tags to be the only acceptable version information. The extended component definition of the SFR remains the same,

i.e. the ECD specifies that application versioning can be done through SWID or through some other measure, and then the body text definition of the SFR forces the ST author to choose only the "SWID" option.

**Comment by jmcdaniels** [comment]
Issue resolved, closing.
