### ISSUE TITLE
FCS_STO_EXT.1 and FCS_PBKDF_EXT.1 are missing some output lengths

### ISSUE THREAD

**Issue by jvdsn** [commoncriteria/application#182]
The PP allows passwords to be conditioned before storage (commonly referred to as "password hashing"[^1][^2]) using PBKDF2[^3] in FCS_STO_EXT.1. This password hashing can be provided by the platform (directly specified in FCS_STO_EXT.1) or implemented by the TOE (which requires the inclusion of FCS_PBKDF_EXT.1).

In FCS_STO_EXT.1, the PP allows HMAC-SHA256, HMAC-SHA384, or HMAC-SHA512 to be used as the PRF in the platform-provided PBKDF2, but only allows an output length of 256 bits.

In FCS_PBKDF_EXT.1, the PP allows any HMAC algorithm specified in FCS_COP.1/KeyedHash (currently, HMAC-SHA1, HMAC-SHA256, HMAC-SHA384, or HMAC-SHA512) and output lengths of 128 or 256 bits.

PBKDF2 internally uses the HMAC output, which corresponds to the underlying hash length, so an output length of 384 or 512 bits is an obvious choice when HMAC-SHA384 resp. HMAC-SHA512 are used. It seems that some output lengths for password hashing are therefore missing from the PP.

Rather than going through the effort of listing each output size individually, I think it's probably just easier to change the text as follows:
* FCS_STO_EXT.1: "cryptographic key size of 256 bits" -> "cryptographic key size of [**assignment**: _positive integer of 256 or more_] bits"
* FCS_PBKDF_EXT.1: "cryptographic key sizes [**selection**: _128, 256_]" -> cryptographic key sizes [**selection**: _128, 256, [**assignment**: _positive integer of 128 or more_]_]"

If desired, I'll gladly open a pull request to implement this change.

[^1]: OWASP: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
[^2]: NIST SP 800-63B: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf (p. 15)
[^3]: NIST SP 800-132: https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf

**Comment by jmcdaniels** [comment]
Added.  AES 128 is planned to be removed this update so only assignment 256 or greater included.
